//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GisDes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Integrantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Integrantes()
        {
            this.SemilleroInvestigacion = new HashSet<SemilleroInvestigacion>();
        }
    
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Ocupación { get; set; }
        public string Tipo { get; set; }
        public int ID { get; set; }
        public string CvLAC { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemilleroInvestigacion> SemilleroInvestigacion { get; set; }
    }
}
