//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GisDes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaExterna
    {
        public decimal Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public decimal Cedula { get; set; }
        public System.DateTime Fechaingreso { get; set; }
        public string Ocupacion { get; set; }
        public bool Estado { get; set; }
    }
}
