//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISDES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        public decimal Id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Cvlac { get; set; }
        public string Intereses { get; set; }
        public string Departamento { get; set; }
        public bool Estado { get; set; }
    }
}
